#include <errors.h>

char RESTXT[RES_LAST][RESTXT_MAX_DESCRIPTION_CHARS-1] =
{
    // OK IGNORED
    "ERROR: OUT OF MEMORY",
    "ERROR: INVALID POINTER",
    "ERROR: INVALID ARGUMENT"
    "ERROR: VALUE NOT FOUND",
    "ERROR: NO DATA",
    "ERROR: CORRUPTED DATA",
    "ERROR: UNSUPPORTED PARAMETER",
    "ERROR: NOT IMPLEMENTED"
    // LAST IGNORED
};

