#!/bin/sh
module="simple_int"
device="port"
mode="664"

# invoke insmod with all arguments we got
insmod $module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Create an entry point. We only need one in this case.
rm -f /dev/${device}0
mknod /dev/${device}0 c $major 0

chmod $mode  /dev/${device}0






